#ifndef _FOCAL_DEF_H_
#define _FOCAL_DEF_H_

#include <stdint.h>
#ifndef NULL
#define NULL    ((void*)(0x00))
#endif

typedef enum {
    FOCAL_DEF_OK ,
    FOCAL_DEF_WAIT_EVENT_FINGER_PRESENT,
    FOCAL_DEF_CAPTURE_DONE,
    FOCAL_DEF_ENABLE_EVENT_FINGER_PRESENT,
    FOCAL_DEF_WAIT_TIME,
    FOCAL_DEF_FINGER_PRESENT,
    FOCAL_DEF_FINGER_ON,
    FOCAL_DEF_FINGER_LOST,
    FOCAL_DEF_ERROR_TOO_FAST,
    FOCAL_DEF_ERROR_TOO_SLOW,
    FOCAL_DEF_ERROR_GENERAL,
    FOCAL_DEF_ERROR_SENSOR,
    FOCAL_DEF_ERROR_MEMORY,
    FOCAL_DEF_ERROR_PARAMETER,
    FOCAL_DEF_ERROR_SIZE,
    FOCAL_DEF_ERROR_MEM,
    FOCAL_DEF_ERROR_TAC,
    FOCAL_DEF_ERROR_PARMETER, 
} focal_def_return_t;

#define FOCAL_DEF_RET_FROM_LIB_RET(r) ((focal_def_return_t) r)

#define FOCAL_DEF_TEMPLATE_DB_MAX_SIZE    (1024 * 500)

#define FOCAL_DEF_MAX_ID_COUNT            30
#define FOCAL_DEF_IMAGE_SIZE              (208 * 80)

#define FOCAL_DEF_EVENT_FINGER_DOWN       1
#define FOCAL_DEF_EVENT_WAITING_FINGER    2
#define FOCAL_DEF_EVENT_FINGER_UP         3
#define FOCAL_DEF_EVENT_IDENTIFY_SUCCESS  4
#define FOCAL_DEF_EVENT_IDENTIFY_FAILED   5
#define FOCAL_DEF_EVENT_ENROLLED_SUCCESS  6
#define FOCAL_DEF_EVENT_ENROLLED_FAILED   7
#define FOCAL_DEF_EVENT_PROGRESS          8

#define FOCAL_DEF_EXT_DATA_DIRECTION_OF_NEXT_TOUCH    0
#define FOCAL_DEF_EXT_DATA_MAIN_CLUSTER_IDENTIFIED    1

#define FOCAL_DEF_EXT_DATA_NEXT_TOUCH                 2

#define FOCAL_DEF_EXT_DATA_LAST_TOUCH  (2 + 8)

#define FOCAL_DEF_EXT_DATA_NR_OF_MASKS (2 + 2 * 8)

#define FOCAL_DEF_EXT_DATA_MASK_LIST   (3 + 2 * 8)


#endif /* _FOCAL_DEF_H_ */
